### PR TITLE
Add shared gpu resources patchset

### PR DESCRIPTION
**Pull request by Iglu47**
"Add initial support for shared gpu resources.
Disabled by default since these patches are only in **Proton Experimental**.
Requires DXVK 1.10.3+, VKD3D-Proton 2.7+"

https://github.com/doitsujin/dxvk/pull/2516
https://github.com/doitsujin/dxvk/pull/2608

these patches are enough to make video work in `Neighbors Back From Hell` (Unity engine)
https://github.com/ValveSoftware/wine/commit/649717ad0a34e07886fd2568623b5e33b2a875f3:
```
With this and the previous two patches, some video playback bugs
are solved for some games (e.g. Trailmakers, Rustler, TOHU and
others) when using DXVK (wined3d doesn't currently support
shared resources, so there is no way to check with it).
```
but maybe other videos will need more patches from Giovanni Mascellani related to CW-Bug-Id: **#19126**

UPD. added https://github.com/Guy1524/wine/commits/crysis-remastered-fixes (thanks @Guy1524)
which contains the latest changes
```
fixes a lot of bugs and gets crysis remastered RT working
```

### CODE REVIEW

**Comment by Iglu47** [comment]
I'll look tomorrow how to add the rest of Derek's patches, but probably will be need help with testing

**Comment by Iglu47** [comment]
I will try to expand the patchset before merging
(to both https://github.com/Guy1524/wine/commits/shared-resources and https://github.com/Guy1524/wine/commits/halo-infinite-fixes )

**Comment by Iglu47** [comment]
just syncing with Proton `experimental_7.0`

**Comment by Iglu47** [comment]
updated to https://github.com/Guy1524/wine/commits/crysis-remastered-fixes (thanks @Guy1524)
need help with testing

**Comment by Iglu47** [comment]
should be fine anyway since it is disabled by default

**Comment by Tk-Glitch** [comment]
Nice addition. Thanks for bringing this to newer trees. Thanks to @Guy1524 for the patchset as I know it wasn't an easy task !
:frog: :heart:

**Pull request merged**
