### PR TITLE
Fix conhost.exe taking 100% cpu with fsync.

### PR DESCRIPTION
**Pull request by openglfreak**

### CODE REVIEW

**Comment by openglfreak** [comment]
:thinking: Now Overwatch doesn't start, neither with esync nor with fsync. I'll try without this change

**Comment by openglfreak** [comment]
Ok, good news is it's not this change's fault, bad news is it also doesn't start without this change...

**Comment by Tk-Glitch** [comment]
The conhost issue is gone on my end so far. Has been for weeks.

**Comment by openglfreak** [comment]
It's not gone for me. Look at the changes in this PR, they make sense, right?

**Comment by Tk-Glitch** [comment]
Absolutely

**Pull request merged**
